image: jdrouet/docker-with-buildx:stable

stages:
  - test
  - build
  - deploy

test:
  image: node:12.17.0
  tags: 
    - docker
  stage: test
  script:
    - npm install
    - npm run test
  coverage: /All\sfiles.*?\s+(\d+.\d+)/

build:
  stage: build
  tags:
    - docker
  script:
    - docker build --tag registry.stratus.services/stratus/alertin .
    - docker push "registry.stratus.services/stratus/alertin"

deploy:
  stage: deploy
  tags: 
    - shell
  script: 
    - 'ssh root@pi /home/scripts/docker-reinstall-alertin'
    - 'ssh root@pi /home/scripts/update-alertin-git'
